### ISSUE TITLE
[feature request] add stats in home timeline

### ISSUE THREAD

**Issue by chrisschm** [tuskyapp/Tusky#2486]
[add stats in home timeline].

I am missing (while browsing the timelines) to see if any comment, share or fav is made on each toot. Would be nice to have those stats without the need going inside a toot.

* * * *
- Tusky Version: 17.0
- Android Version: 12
- Android Device: Google Pixel 5
- Mastodon instance (if applicable): norden.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by davidbtc2009** [comment]
This looks to have been solved in tusky 19. Have you checked it out and is that what you were after?

**Comment by chrisschm** [comment]
> 

I'm sorry. I've closed my mastodon account and can not check anymore if that is solved.

**Comment by davidbtc2009** [comment]
> > 
> 
> I'm sorry. I've closed my mastodon account and can not check anymore if that is solved.

Closing your mastodon account is sad. Here is a screenshot
![Screenshot_20220723-102858_Tusky](https://user-images.githubusercontent.com/67274571/180609507-36db77a0-168f-4e3e-a06b-10429a8ed7b1.png)

**Comment by chrisschm** [comment]
Than it's not fixed. At the first post, it is a boost and so i would think there should be at minimum a 1 close to the boost button.

But the 0 close to the answer buttons seems to be the right direction.

**Comment by davidbtc2009** [comment]
> Than it's not fixed. At the first post, it is a boost and so i would think there should be at minimum a 1 close to the boost button.
> 
> But the 0 close to the answer buttons seems to be the right direction.

Ah, i see what you mean

**Comment by domenukk** [comment]
For me, the information how many people interacted with a toot is interesting metadata, and I don't want to click on everything just to see that.
Would love to see this feature implemented (as option)
